name: Deploy Arena Connect

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup SSH Agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      # 3. Deploy to VPS
      - name: Deploy Code to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ndaruu@103.150.117.116 << 'EOF'
            cd /var/www/arena-connect_api
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            chown -R www-data:www-data /var/www/arena-connect_api
          EOF
